services:
  watcherr:
    build: .
    restart: unless-stopped
    environment:
      DB_URL: ${DB_URL}
      METRICS_PORT: ${METRICS_PORT}
      RESEND_API_KEY: ${RESEND_API_KEY}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME}
      EMAIL_TO: ${EMAIL_TO}
      EMAIL_SUBJECT: ${EMAIL_SUBJECT}
